title: Isidro Dumas
description: Isidro Dumas writes
author: Isidro Dumas
github: https://github.com/isidrodumas
about: Manunulat tungkol sa Stoicism, Self Development, at Mental Health
disqus_shortname: https-isidrodumas-com
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/isidrodumaswrites"
    - icon: fa-twitter
      link: "https://twitter.com/isidrodumas"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/isidrodumas"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/

url: "https://isidrodumas.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
